runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /example\.html
  static_files: example.html
  upload: example\.html

- url: /tester.php
  script: tester.php

- url: .*
  script: index.php

skip_files:
  - google-cloud-sdk/